name: initialize
description: 'Initializes the project using Gradle'
runs:
  using: composite
  steps:
    - name: executable
      shell: bash
      run: chmod a+x ./gradlew

    - name: setup jdk
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'corretto'

    - name: apply version to properties and variables
      shell: bash
      run: |
        export version=$(echo ${GITHUB_REF##*/} | sed 's/^v//')
        echo "version=$version" > ./version.properties
        echo "##[set-output name=version;]$version"