name: Publish

on:
  release:
    types: [ created ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: executable
        run: chmod a+x ./gradlew

      - name: setup jdk
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: increment version
        uses: gradle/gradle-build-action@v2
        with:
          arguments: incrementSemanticVersion

      - name: build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :api:build

      - name: publish
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :api:publish
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: apply version to repository
        run: |
          git config user.name ${{ github.actor }}
          git config user.email ${{ github.actor }}@users.noreply.github.com
          git add ./version.properties
          git commit -m "Apply version to repository"
          git push