name: Release

on:
  push:
    tags:
      - v*

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: init
        uses: ./.github/actions/init

      - name: build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

  publish-to-release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: init
        uses: ./.github/actions/init

      - name: jar
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :api:jar

      - name: release
        uses: ncipollo/release-action@v1
        with:
          name: release ${{ env.VERSION }}
          artifacts: "api/build/libs/mfm-*.jar"
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  publish-to-package:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: init
        uses: ./.github/actions/init

      - name: generate docs
        uses: gradle/gradle-build-action@v2
        with:
          arguments: dokkaHtml

      - name: upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: build/dokka/html

      - name: deploy to GitHub Pages
        uses: actions/deploy-pages@v2