name: Release

on:
  push:
    tags:
      - v*

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: init
        uses: ./.github/actions/init

      - name: build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

  publish-release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: init
        id: init
        uses: ./.github/actions/init

      - name: jar
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :api:jar

      - name: release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ steps.init.outputs.version }}
          artifacts: "api/build/libs/mfm-*.jar"
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: publish
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :api:publish
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  build-docs:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: init
        uses: ./.github/actions/init

      - name: generate docs
        uses: gradle/gradle-build-action@v2
        with:
          arguments: dokkaHtml

      - name: upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: build/dokka/html

  deploy-docs:
    runs-on: ubuntu-latest
    needs: build-docs
    environment:
      name: mfm.kt docs
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2